default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    run_tests(
      scheme: "Stride",
      device: "iPhone 16",
      clean: true
    )
  end

  desc "Build ad hoc IPA for direct distribution"
  lane :adhoc do
    setup_ci if ENV["CI"]

    match(type: "adhoc", readonly: is_ci)

    build_app(
      scheme: "Stride",
      export_method: "ad-hoc",
      configuration: "Release"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
    )

    match(type: "development", readonly: is_ci)

    increment_build_number(
      build_number: latest_testflight_build_number(api_key: api_key) + 1
    )

    build_app(
      scheme: "Stride",
      export_method: "development",
      configuration: "Debug"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      groups: ["Stride Testers"]
    )
  end
end
